FROM golang:1.5
ADD GLOCKFILE src/github.com/dcoker/secrets/
ADD Makefile src/github.com/dcoker/secrets/
WORKDIR src/github.com/dcoker/secrets
RUN make glock-sync
ADD . .
RUN make build
WORKDIR tests
RUN ./tests.sh
